spring.application.name=habit.management


#JWT CONFIG
jwt.expiration.time = 86400

##POSTGRES CONFIG
spring.datasource.url=jdbc:postgresql://localhost:15432/db_habit_app
spring.datasource.username=admin123
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect